<option value="Advocacy Group">Advocacy Group</option>
<option value="After School">After School</option>
<option value="Boarding">Boarding</option>
<option value="Catholic">Catholic</option>
<option value="Charter">Charter</option>
<option value="Clinic">Clinic</option>
<option value="College">College</option>
<option value="College Prep">College Prep</option>
<option value="Country Day">Country Day School</option>
<option value="Reviewer">Curricula Reviewer(s)</option>
<option value="Day School">Day School</option>
<option value="Episcopal">Episcopal</option>
<option value="Friends">Friends School</option>
<option value="Health Services">Health Services</option>
<option value="Holistic">Holistic</option>
<option value="Home School">Home School</option>
<option value="IB School">IB School</option>
<option value="Immersion (Chinese)">Immersion (Chinese)</option>
<option value="Immersion (Spanish)">Immersion (Spanish)</option>
<option value="Immersion (French)">Immersion (French)</option>
<option value="Independent">Independent School</option>
<option value="Independent Sex Educator">Independent Sex Educator</option>
<option value="International">International</option>
<option value="Jewish">Jewish</option>
<option value="Magnet">Magnet</option>
<option value="Methodist">Methodist</option>
<option value="Montessori">Montessori</option>
<option value="Nonprofit">Nonprofit</option>
<option value="Other">Other</option>
<option value="Progressive">Progressive</option>
<option value="Private">Private</option>
<option value="Private special education">Private Special Education</option>
<option value="Public">Public</option>
<option value="Public Charter">Public Charter</option>
<option value="Public virtual">Public virtual</option>
<option value="Reggio Emilia">Reggio Emilia</option>
<option value="Residential Treatment Facility">Residential Treatment Facility</option>
<option value="Social Services">Social Services</option>
<option value="Therapeutic Practice">Therapeutic Practice</option>
<option value="University">University</option>
<option value="UU">UU</option>
<option value="Waldorf">Waldorf</option>

